# Shell
shell zsh

# Editor
editor /usr/bin/nvim

# Fonts
font_family      family = "JetBrainsMono Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto

# Size
font_size 12.0

# Theme
include ~/.local/share/themes/catppuccin-mocha.conf

# Key map
# Window Manging
# kitty_mod is cntrl+shift by default
map --new-mode wm kitty_mod+w

# Switch focus to the neighboring window
map --mode wm h neighboring_window left
map --mode wm j neighboring_window down 
map --mode wm k neighboring_window up
map --mode wm l neighboring_window right

# Move the active window 
map --mode wm shift+h move_window left
map --mode wm shift+j move_window down
map --mode wm shift+k move_window up
map --mode wm shift+l move_window right

# Resize the active window
map --mode wm n resize_window narrower
map --mode wm w resize_window wider
map --mode wm t resize_window taller
map --mode wm s resize_window shorter

# Exit the manage window mode
map --mode wm esc pop_keyboard_mode

