# reload config
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"

# prefix
unbind C-a
set -g prefix C-a
bind C-a send-prefix

# mouse
set -g mouse on

# index
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# command history cash
set-option -g history-limit 5000

# panel
set-option -g status-position top

# session
unbind d
bind-key -n C-d detach

# window
bind d kill-window
unbind C-Tab
bind-key -n C-Tab next-window
unbind C-S-Tab
bind-key -n C-S-Tab previous-window
# open new window at the current directory
tmux new-window -c "#{pane_current_path}"

# pane
# pane navigation
# use this instead of installing vim-tmux-navigator for tmux
bind-key -n C-h select-pane -L
bind-key -n C-j select-pane -D
bind-key -n C-k select-pane -U
bind-key -n C-l select-pane -R

# pane split
unbind %
unbind |
bind | split-window -hc "#{pane_current_path}"
bind "\\" split-window -fh -c "#{pane_current_path}"
unbind '"'
unbind -
bind - split-window -vc "#{pane_current_path}"
bind "_" split-window -fv -c "#{pane_current_path}"

# plugins
set -g @plugin 'tmux-plugins/tpm' 
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'catppuccin/tmux'
# set -g @plugin 'christoomey/vim-tmux-navigator'

# configure catppuccin
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "basic"

# set -g @thm_fg "#{@thm_crust}"
set -g @catppuccin_status_background "#{@thm_bg}"

set -g @catppuccin_window_text " #W"
set -g @catppuccin_status_right_separator "█"
set -g @catppuccin_status_left_separator "█"
set -g @catppuccin_window_text_color "#{@thm_mantle}"
set -g @catppuccin_window_number_color "#{@thm_blue}"

set -g @catppuccin_window_current_text " #W"
set -g @catppuccin_window_current_text_color "#{@thm_mantle}"
set -g @catppuccin_window_current_number_color "#{@thm_red}"

# modules
set -g status-right "#{E:@catppuccin_status_session}"
set -g @catppuccin_status_module_bg_color "#{@thm_crust}"
# set -g @catppuccin_session_color "blue"
set -g @catppuccin_status_session_text_fg "blue"
set -g @catppuccin_menu_selected_style "fg=#{@thm_yellow},bold,bg=#{@thm_blue}"

set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""


# Initialize TMUX plugin manager
run ~/.config/tmux/plugins/tpm/tpm

# fix later
# set -g status-style "bg=#181825,fg=#{@thm_crust}"
# set -gF popup-style "bg=#{@thm_bg},fg=#{@thm_blue}"
# set -gF popup-border-style "fg=#{@thm_blue}"
# set -gF menu-selected-style "fg=#{@thm_blue},bold,bg=#{@thm_bg}"

